// This file was autogenerated from Tests/html5lib/tokenizer/pendingSpecChanges.test.

#import <SenTestingKit/SenTestingKit.h>
#import "HTMLTokenizerTestUtilities.h"

@interface TokenizerPendingSpecChangesTests : SenTestCase

@end

@implementation TokenizerPendingSpecChangesTests
        
- (void)test0
{
    NSArray *tokens = @[@"ParseError",@"ParseError",@[@"Comment",@"-- >"]];
    for (NSString *state in @[@""]) {
        HTMLTokenizer *tokenizer = [[HTMLTokenizer alloc] initWithString:@"<!---- >" state:StateNamed(state)];
        STAssertEqualObjects(tokenizer.allObjects, ReifiedTokensForTestTokens(tokens), @"%@", @"<!---- >");
    }
}

@end
